#!/bin/bash
# =============================================================================
#  @@-COPYRIGHT-START-@@
#
#  Copyright (c) 2016-2021, Qualcomm Innovation Center, Inc. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#  1. Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
#  3. Neither the name of the copyright holder nor the names of its contributors
#     may be used to endorse or promote products derived from this software
#     without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  SPDX-License-Identifier: BSD-3-Clause
#
#  @@-COPYRIGHT-END-@@
# =============================================================================
#
# Hook to check whether each commit is DCO-signed and validate internal user email domain
#

test "" = "$(grep '^Signed-off-by: ' "$1" |
	sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 "Duplicate Signed-off-by lines in commit message. Aborting commit."
	exit 1
}

AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1

if [ "$(grep '^Signed-off-by: ' "$1" | wc -l)" -le 0 ]; then
	echo >&2 "Error: Commit was not signed off."
	SOB=$(echo ${AUTHORINFO} | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
	echo >&2 "Please use the \"git commit -s \" option OR"
	echo >&2 "Append the following text to your commit message:"
	echo >&2 "  $SOB"
	echo >&2 "Aborting commit."
	exit 1
fi

FORBIDDEN_DOMAIN="qualcomm.com"
EMAIL_DOMAIN=$(printf '%s\n' "$AUTHORINFO" | grep -o "${FORBIDDEN_DOMAIN}")
if [[ "$EMAIL_DOMAIN" == "${FORBIDDEN_DOMAIN}" ]]; then
	echo >&2 "Error: Invalid email domain. Please commit with the correct email domain name."
	echo >&2 "  Your author information was $AUTHORINFO."
	echo >&2 "  Your remote information was $GITREMOTE."
	echo >&2 "Run the following in your local repository and then re-try your commit:"
	echo >&2 "  git config user.email \"quic_${USER}@quicinc.com\" "
	exit 1
fi
